In [1]:
print("OK")

OK

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("dataset.csv")
df.head()

,datetime,datetimeEpoch,tempmax,tempmin,temp,feelslikemax,feelslikemin,feelslike,dew,humidity,...,City,Temp_Range,Heat_Index,Severity_Score,Condition_Code,Month,Season,Day_of_Week,Is_Weekend,Health_Risk_Score
0,2024-09-07,1.725692e+09,106.1,91.0,98.5,104.0,88.1,95.9,51.5,21.0,...,Phoenix,15.1,95.918703,4.4300,NaN,9.0,Fall,Saturday,True,10.522170
1,2024-09-08,1.725779e+09,103.9,87.0,95.4,100.5,84.7,92.3,48.7,21.5,...,Phoenix,16.9,92.281316,3.8800,0.0,9.0,Fall,Sunday,True,10.062332
2,2024-09-09,1.725865e+09,105.0,83.9,94.7,99.9,81.6,90.6,41.7,16.9,...,Phoenix,21.1,90.599165,3.6300,0.0,9.0,Fall,Monday,False,9.673387
3,2024-09-10,1.725952e+09,106.1,81.2,93.9,100.6,79.5,89.8,39.1,15.7,...,Phoenix,24.9,89.638811,2.8512,0.0,9.0,Fall,Tuesday,False,9.411519
4,2024-09-11,1.726038e+09,106.1,82.1,94.0,101.0,80.0,90.0,40.1,15.9,...,Phoenix,24.0,89.760414,3.3908,0.0,9.0,Fall,Wednesday,False,9.515179

In [4]:
df.shape

(1000, 46)

In [5]:
df.columns

Index(['datetime', 'datetimeEpoch', 'tempmax', 'tempmin', 'temp',
       'feelslikemax', 'feelslikemin', 'feelslike', 'dew', 'humidity',
       'precip', 'precipprob', 'precipcover', 'preciptype', 'snow',
       'snowdepth', 'windgust', 'windspeed', 'winddir', 'pressure',
       'cloudcover', 'visibility', 'solarradiation', 'solarenergy', 'uvindex',
       'severerisk', 'sunrise', 'sunriseEpoch', 'sunset', 'sunsetEpoch',
       'moonphase', 'conditions', 'description', 'icon', 'stations', 'source',
       'City', 'Temp_Range', 'Heat_Index', 'Severity_Score', 'Condition_Code',
       'Month', 'Season', 'Day_of_Week', 'Is_Weekend', 'Health_Risk_Score'],
      dtype='object')

In [6]:
data = df.to_dict(orient="records")
data

[{'datetime': '2024-09-07',
  'datetimeEpoch': 1725692400.0,
  'tempmax': 106.1,
  'tempmin': 91.0,
  'temp': 98.5,
  'feelslikemax': 104.0,
  'feelslikemin': 88.1,
  'feelslike': 95.9,
  'dew': 51.5,
  'humidity': 21.0,
  'precip': 0.0,
  'precipprob': 5.0,
  'precipcover': 0.0,
  'preciptype': nan,
  'snow': 0.0,
  'snowdepth': 0.0,
  'windgust': 26.3,
  'windspeed': 13.7,
  'winddir': 107.3,
  'pressure': 1009.2,
  'cloudcover': 25.0,
  'visibility': 10.0,
  'solarradiation': 261.4,
  'solarenergy': 22.5,
  'uvindex': 9.0,
  'severerisk': 10.0,
  'sunrise': '06:06:50',
  'sunriseEpoch': 1725714410.0,
  'sunset': '18:44:53',
  'sunsetEpoch': 1725759893.0,
  'moonphase': 0.16,
  'conditions': 'Partially cloudy',
  'description': 'Partly cloudy throughout the day.',
  'icon': 'partly-cloudy-day',
  'stations': "['KSDL', 'KDVT', 'AZM15', 'KPHX']",
  'source': 'comb',
  'City': 'Phoenix',
  'Temp_Range': 15.099999999999994,
  'Heat_Index': 95.91870310999995,
  'Severity_Score': 4.43,
  'Condition_Code': nan,
  'Month': 9.0,
  'Season': 'Fall',
  'Day_of_Week': 'Saturday',
  'Is_Weekend': True,
  'Health_Risk_Score': 10.522170310999996},
 {'datetime': '2024-09-08',
  'datetimeEpoch': 1725778800.0,
  'tempmax': 103.9,
  'tempmin': 87.0,
  'temp': 95.4,
  'feelslikemax': 100.5,
  'feelslikemin': 84.7,
  'feelslike': 92.3,
  'dew': 48.7,
  'humidity': 21.5,
  'precip': 0.0,
  'precipprob': 3.0,
  'precipcover': 0.0,
  'preciptype': nan,
  'snow': 0.0,
  'snowdepth': 0.0,
  'windgust': 20.8,
  'windspeed': 12.8,
  'winddir': 101.5,
  'pressure': 1008.8,
  'cloudcover': 13.5,
  'visibility': 10.1,
  'solarradiation': 293.3,
  'solarenergy': 25.2,
  'uvindex': 9.0,
  'severerisk': 10.0,
  'sunrise': '06:07:30',
  'sunriseEpoch': 1725800850.0,
  'sunset': '18:43:32',
  'sunsetEpoch': 1725846212.0,
  'moonphase': 0.19,
  'conditions': 'Clear',
  'description': 'Clear conditions throughout the day.',
  'icon': 'clear-day',
  'stations': nan,
  'source': 'fcst',
  'City': 'Phoenix',
  'Temp_Range': 16.900000000000006,
  'Heat_Index': 92.28131624140006,
  'Severity_Score': 3.88,
  'Condition_Code': 0.0,
  'Month': 9.0,
  'Season': 'Fall',
  'Day_of_Week': 'Sunday',
  'Is_Weekend': True,
  'Health_Risk_Score': 10.062331624140006},
 {'datetime': '2024-09-09',
  'datetimeEpoch': 1725865200.0,
  'tempmax': 105.0,
  'tempmin': 83.9,
  'temp': 94.7,
  'feelslikemax': 99.9,
  'feelslikemin': 81.6,
  'feelslike': 90.6,
  'dew': 41.7,
  'humidity': 16.9,
  'precip': 0.0,
  'precipprob': 0.0,
  'precipcover': 0.0,
  'preciptype': nan,
  'snow': 0.0,
  'snowdepth': 0.0,
  'windgust': 18.3,
  'windspeed': 10.3,
  'winddir': 90.8,
  'pressure': 1009.4,
  'cloudcover': 6.2,
  'visibility': 10.1,
  'solarradiation': 327.0,
  'solarenergy': 28.2,
  'uvindex': 9.0,
  'severerisk': 10.0,
  'sunrise': '06:08:10',
  'sunriseEpoch': 1725887290.0,
  'sunset': '18:42:10',
  'sunsetEpoch': 1725932530.0,
  'moonphase': 0.22,
  'conditions': 'Clear',
  'description': 'Clear conditions throughout the day.',
  'icon': 'clear-day',
  'stations': nan,
  'source': 'fcst',
  'City': 'Phoenix',
  'Temp_Range': 21.099999999999994,
  'Heat_Index': 90.5991651058291,
  'Severity_Score': 3.63,
  'Condition_Code': 0.0,
  'Month': 9.0,
  'Season': 'Fall',
  'Day_of_Week': 'Monday',
  'Is_Weekend': False,
  'Health_Risk_Score': 9.67338651058291},
 {'datetime': '2024-09-10',
  'datetimeEpoch': 1725951600.0,
  'tempmax': 106.1,
  'tempmin': 81.2,
  'temp': 93.9,
  'feelslikemax': 100.6,
  'feelslikemin': 79.5,
  'feelslike': 89.8,
  'dew': 39.1,
  'humidity': 15.7,
  'precip': 0.012,
  'precipprob': 0.0,
  'precipcover': 4.17,
  'preciptype': "['rain']",
  'snow': 0.0,
  'snowdepth': 0.0,
  'windgust': 10.5,
  'windspeed': 5.4,
  'winddir': 130.1,
  'pressure': 1006.8,
  'cloudcover': 4.9,
  'visibility': 12.5,
  'solarradiation': 276.8,
  'solarenergy': 24.0,
  'uvindex': 9.0,
  'severerisk': 10.0,
  'sunrise': '06:08:49',
  'sunriseEpoch': 1725973729.0,
  'sunset': '18:40:48',
  'sunsetEpoch': 1726018848.0,
  'moonphase': 0.25,
  'conditions': 'Clear',
  'description': 'Clear conditions throughout the day.',
  'icon': 'clear-day',
  'stations': nan,
  'source': 'fcst',
  'City': 'Phoenix',
  'Temp_Range': 24.89999999999999,
  'Heat_Index': 89.6388106900291,
  'Severity_Score': 2.8512000000000004,
  'Condition_Code': 0.0,
  'Month': 9.0,
  'Season': 'Fall',
  'Day_of_Week': 'Tuesday',
  'Is_Weekend': False,
  'Health_Risk_Score': 9.411519469002911},
 {'datetime': '2024-09-11',
  'datetimeEpoch': 1726038000.0,
  'tempmax': 106.1,
  'tempmin': 82.1,
  'temp': 94.0,
  'feelslikemax': 101.0,
  'feelslikemin': 80.0,
  'feelslike': 90.0,
  'dew': 40.1,
  'humidity': 15.9,
  'precip': 0.008,
  'precipprob': 0.0,
  'precipcover': 4.17,
  'preciptype': "['rain']",
  'snow': 0.0,
  'snowdepth': 0.0,
  'windgust': 15.9,
  'windspeed': 8.1,
  'winddir': 201.6,
  'pressure': 1001.8,
  'cloudcover': 5.7,
  'visibility': 15.0,
  'solarradiation': 274.9,
  'solarenergy': 23.7,
  'uvindex': 9.0,
  'severerisk': 10.0,
  'sunrise': '06:09:29',
  'sunriseEpoch': 1726060169.0,
  'sunset': '18:39:26',
  'sunsetEpoch': 1726105166.0,
  'moonphase': 0.29,
  'conditions': 'Clear',
  'description': 'Clear conditions throughout the day.',
  'icon': 'clear-day',
  'stations': nan,
  'source': 'fcst',
  'City': 'Phoenix',
  'Temp_Range': 24.0,
  'Heat_Index': 89.76041382170003,
  'Severity_Score': 3.3908,
  'Condition_Code': 0.0,
  'Month': 9.0,
  'Season': 'Fall',
  'Day_of_Week': 'Wednesday',
  'Is_Weekend': False,
  'Health_Risk_Score': 9.515178582170003},
 {'datetime': '2024-09-12',
  'datetimeEpoch': 1726124400.0,
  'tempmax': 103.0,
  'tempmin': 81.6,
  'temp': 91.5,
  'feelslikemax': 98.1,
  'feelslikemin': 79.9,
  'feelslike': 87.9,
  'dew': 41.6,
  'humidity': 18.4,
  'precip': 0.0,
  'precipprob': 0.0,
  'precipcover': 0.0,
  'preciptype': nan,
  'snow': 0.0,
  'snowdepth': 0.0,
  'windgust': 21.5,
  'windspeed': 10.7,
  'winddir': 201.9,
  'pressure': 1000.8,
  'cloudcover': 4.0,
  'visibility': 15.0,
  'solarradiation': 272.7,
  'solarenergy': 23.6,
  'uvindex': 9.0,
  'severerisk': 10.0,
  'sunrise': '06:10:09',
  'sunriseEpoch': 1726146609.0,
  'sunset': '18:38:04',
  'sunsetEpoch': 1726191484.0,
  'moonphase': 0.32,
  'conditions': 'Clear',
  'description': 'Clear conditions throughout the day.',
  'icon': 'clear-day',
  'stations': nan,
  'source': 'fcst',
  'City': 'Phoenix',
  'Temp_Range': 21.40000000000001,
  'Heat_Index': 87.60290690670004,
  'Severity_Score': 3.95,
  'Condition_Code': 0.0,
  'Month': 9.0,
  'Season': 'Fall',
  'Day_of_Week': 'Thursday',
  'Is_Weekend': False,
  'Health_Risk_Score': 9.487090690670003},
 {'datetime': '2024-09-13',
  'datetimeEpoch': 1726210800.0,
  'tempmax': 101.2,
  'tempmin': 77.6,
  'temp': 89.3,
  'feelslikemax': 96.9,
  'feelslikemin': 77.6,
  'feelslike': 86.4,
  'dew': 42.6,
  'humidity': 20.4,
  'precip': 0.0,
  'precipprob': 0.0,
  'precipcover': 0.0,
  'preciptype': nan,
  'snow': 0.0,
  'snowdepth': 0.0,
  'windgust': 14.3,
  'windspeed': 7.2,
  'winddir': 192.9,
  'pressure': 1006.3,
  'cloudcover': 7.2,
  'visibility': 15.0,
  'solarradiation': 269.5,
  'solarenergy': 23.1,
  'uvindex': 9.0,
  'severerisk': 10.0,
  'sunrise': '06:10:49',
  'sunriseEpoch': 1726233049.0,
  'sunset': '18:36:41',
  'sunsetEpoch': 1726277801.0,
  'moonphase': 0.36,
  'conditions': 'Clear',
  'description': 'Clear conditions throughout the day.',
  'icon': 'clear-day',
  'stations': nan,
  'source': 'fcst',
  'City': 'Phoenix',
  'Temp_Range': 23.60000000000001,
  'Heat_Index': 85.71988263588409,
  'Severity_Score': 3.2300000000000004,
  'Condition_Code': 0.0,
  'Month': 9.0,
  'Season': 'Fall',
  'Day_of_Week': 'Friday',
  'Is_Weekend': False,
  'Health_Risk_Score': 9.23090826358841},
 {'datetime': '2024-09-14',
  'datetimeEpoch': 1726297200.0,
  'tempmax': 99.4,
  'tempmin': 78.2,
  'temp': 89.1,
  'feelslikemax': 96.1,
  'feelslikemin': 78.2,
  'feelslike': 86.8,
  'dew': 48.4,
  'humidity': 25.3,
  'precip': 0.004,
  'precipprob': 6.0,
  'precipcover': 4.17,
  'preciptype': "['rain']",
  'snow': 0.0,
  'snowdepth': 0.0,
  'windgust': 12.1,
  'windspeed': 5.4,
  'winddir': 224.8,
  'pressure': 1008.7,
  'cloudcover': 9.6,
  'visibility': 15.0,
  'solarradiation': 262.5,
  'solarenergy': 22.6,
  'uvindex': 9.0,
  'severerisk': 10.0,
  'sunrise': '06:11:29',
  'sunriseEpoch': 1726319489.0,
  'sunset': '18:35:19',
  'sunsetEpoch': 1726364119.0,
  'moonphase': 0.39,
  'conditions': 'Clear',
  'description': 'Clear conditions throughout the day.',
  'icon': 'clear-day',
  'stations': nan,
  'source': 'fcst',
  'City': 'Phoenix',
  'Temp_Range': 21.200000000000003,
  'Heat_Index': 86.11250590362911,
  'Severity_Score': 3.0104,
  'Condition_Code': 0.0,
  'Month': 9.0,
  'Season': 'Fall',
  'Day_of_Week': 'Saturday',
  'Is_Weekend': True,
  'Health_Risk_Score': 9.37288179036291},
 {'datetime': '2024-09-15',
  'datetimeEpoch': 1726383600.0,
  'tempmax': 100.1,
  'tempmin': 82.1,
  'temp': 92.0,
  'feelslikemax': 100.6,
  'feelslikemin': 81.5,
  'feelslike': 92.3,
  'dew': 60.3,
  'humidity': 35.8,
  'precip': 0.012,
  'precipprob': 12.9,
  'precipcover': 4.17,
  'preciptype': "['rain']",
  'snow': 0.0,
  'snowdepth': 0.0,
  'windgust': 19.0,
  'windspeed': 11.6,
  'winddir': 254.3,
  'pressure': 1007.3,
  'cloudcover': 1.8,
  'visibility': 14.0,
  'solarradiation': 259.9,
  'solarenergy': 22.3,
  'uvindex': 8.0,
  'severerisk': 30.0,
  'sunrise': '06:12:09',
  'sunriseEpoch': 1726405929.0,
  'sunset': '18:33:56',
  'sunsetEpoch': 1726450436.0,
  'moonphase': 0.42,
  'conditions': 'Clear',
  'description': 'Clear conditions throughout the day.',
  'icon': 'clear-day',
  'stations': nan,
  'source': 'fcst',
  'City': 'Phoenix',
  'Temp_Range': 18.0,
  'Heat_Index': 92.16758603040012,
  'Severity_Score': 3.5012,
  'Condition_Code': 0.0,
  'Month': 9.0,
  'Season': 'Fall',
  'Day_of_Week': 'Sunday',
  'Is_Weekend': True,
  'Health_Risk_Score': 10.470188203040012},
 {'datetime': '2024-09-16',
  'datetimeEpoch': 1726470000.0,
  'tempmax': 99.6,
  'tempmin': 86.1,
  'temp': 92.2,
  'feelslikemax': 99.7,
  'feelslikemin': 87.4,
  'feelslike': 93.0,
  'dew': 62.2,
  'humidity': 37.8,
  'precip': 0.0,
  'precipprob': 12.9,
  'precipcover': 0.0,
  'preciptype': nan,
  'snow': 0.0,
  'snowdepth': 0.0,
  'windgust': 17.7,
  'windspeed': 12.1,
  'winddir': 222.5,
  'pressure': 1006.8,
  'cloudcover': 12.2,
  'visibility': 15.0,
  'solarradiation': 245.3,
  'solarenergy': 21.3,
  'uvindex': 8.0,
  'severerisk': 30.0,
  'sunrise': '06:12:49',
  'sunriseEpoch': 1726492369.0,
  'sunset': '18:32:33',
  'sunsetEpoch': 1726536753.0,
  'moonphase': 0.46,
  'conditions': 'Clear',
  'description': 'Clear conditions throughout the day.',
  'icon': 'clear-day',
  'stations': nan,
  'source': 'fcst',
  'City': 'Phoenix',
  'Temp_Range': 13.5,
  'Heat_Index': 93.20895235529596,
  'Severity_Score': 3.37,
  'Condition_Code': 0.0,
  'Month': 9.0,
  'Season': 'Fall',
  'Day_of_Week': 'Monday',
  'Is_Weekend': False,
  'Health_Risk_Score': 10.594755235529597},
 {'datetime': '2024-09-17',
  'datetimeEpoch': 1726556400.0,
  'tempmax': 100.7,
  'tempmin': 85.7,
  'temp': 92.2,
  'feelslikemax': 98.5,
  'feelslikemin': 85.2,
  'feelslike': 91.2,
  'dew': 57.3,
  'humidity': 31.8,
  'precip': 0.0,
  'precipprob': 19.4,
  'precipcover': 0.0,
  'preciptype': nan,
  'snow': 0.0,
  'snowdepth': 0.0,
  'windgust': 21.5,
  'windspeed': 18.3,
  'winddir': 234.6,
  'pressure': 1005.6,
  'cloudcover': 34.7,
  'visibility': 15.0,
  'solarradiation': 246.5,
  'solarenergy': 21.2,
  'uvindex': 8.0,
  'severerisk': 10.0,
  'sunrise': '06:13:29',
  'sunriseEpoch': 1726578809.0,
  'sunset': '18:31:10',
  'sunsetEpoch': 1726623070.0,
  'moonphase': 0.5,
  'conditions': 'Partially cloudy',
  'description': 'Partly cloudy throughout the day.',
  'icon': 'partly-cloudy-day',
  'stations': nan,
  'source': 'fcst',
  'City': 'Phoenix',
  'Temp_Range': 15.0,
  'Heat_Index': 91.13188727945612,
  'Severity_Score': 3.75,
  'Condition_Code': nan,
  'Month': 9.0,
  'Season': 'Fall',
  'Day_of_Week': 'Tuesday',
  'Is_Weekend': False,
  'Health_Risk_Score': 10.305688727945611},
 {'datetime': '2024-09-18',
  'datetimeEpoch': 1726642800.0,
  'tempmax': 98.3,
  'tempmin': 83.2,
  'temp': 90.1,
  'feelslikemax': 93.5,
  'feelslikemin': 80.7,
  'feelslike': 86.4,
  'dew': 39.2,
  'humidity': 17.4,
  'precip': 0.0,
  'precipprob': 6.5,
  'precipcover': 0.0,
  'preciptype': nan,
  'snow': 0.0,
  'snowdepth': 0.0,
  'windgust': 15.7,
  'windspeed': 10.1,
  'winddir': 247.2,
  'pressure': 1007.1,
  'cloudcover': 0.0,
  'visibility': 15.0,
  'solarradiation': 267.3,
  'solarenergy': 23.1,
  'uvindex': 9.0,
  'severerisk': 10.0,
  'sunrise': '06:14:09',
  'sunriseEpoch': 1726665249.0,
  'sunset': '18:29:47',
  'sunsetEpoch': 1726709387.0,
  'moonphase': 0.52,
  'conditions': 'Clear',
  'description': 'Clear conditions throughout the day.',
  'icon': 'clear-day',
  'stations': nan,
  'source': 'fcst',
  'City': 'Phoenix',
  'Temp_Range': 15.099999999999994,
  'Heat_Index': 86.20360304705606,
  'Severity_Score': 3.37,
  'Condition_Code': 0.0,
  'Month': 9.0,
  'Season': 'Fall',
  'Day_of_Week': 'Wednesday',
  'Is_Weekend': False,
  'Health_Risk_Score': 9.206740304705606},
 {'datetime': '2024-09-19',
  'datetimeEpoch': 1726729200.0,
  'tempmax': 97.4,
  'tempmin': 81.8,
  'temp': 89.1,
  'feelslikemax': 92.2,
  'feelslikemin': 79.6,
  'feelslike': 85.3,
  'dew': 29.0,
  'humidity': 12.4,
  'precip': 0.0,
  'precipprob': 6.5,
  'precipcover': 0.0,
  'preciptype': nan,
  'snow': 0.0,
  'snowdepth': 0.0,
  'windgust': 12.5,
  'windspeed': 8.7,
  'winddir': 258.9,
  'pressure': 1007.8,
  'cloudcover': 9.6,
  'visibility': 15.0,
  'solarradiation': 271.1,
  'solarenergy': 23.4,
  'uvindex': 9.0,
  'severerisk': 10.0,
  'sunrise': '06:14:50',
  'sunriseEpoch': 1726751690.0,
  'sunset': '18:28:24',
  'sunsetEpoch': 1726795704.0,
  'moonphase': 0.56,
  'conditions': 'Clear',
  'description': 'Clear conditions throughout the day.',
  'icon': 'clear-day',
  'stations': nan,
  'source': 'fcst',
  'City': 'Phoenix',
  'Temp_Range': 15.600000000000009,
  'Heat_Index': 85.14708197583606,
  'Severity_Score': 3.05,
  'Condition_Code': 0.0,
  'Month': 9.0,
  'Season': 'Fall',
  'Day_of_Week': 'Thursday',
  'Is_Weekend': False,
  'Health_Risk_Score': 8.892908197583605},
 {'datetime': '2024-09-20',
  'datetimeEpoch': 1726815600.0,
  'tempmax': 94.6,
  'tempmin': 82.5,
  'temp': 87.9,
  'feelslikemax': 89.9,
  'feelslikemin': 80.1,
  'feelslike': 84.4,
  'dew': 35.5,
  'humidity': 15.8,
  'precip': 0.004,
  'precipprob': 6.5,
  'precipcover': 4.17,
  'preciptype': "['rain']",
  'snow': 0.0,
  'snowdepth': 0.0,
  'windgust': 15.4,
  'windspeed': 9.8,
  'winddir': 238.1,
  'pressure': 1007.4,
  'cloudcover': 92.0,
  'visibility': 15.0,
  'solarradiation': 175.8,
  'solarenergy': 15.3,
  'uvindex': 6.0,
  'severerisk': 10.0,
  'sunrise': '06:15:30',
  'sunriseEpoch': 1726838130.0,
  'sunset': '18:27:01',
  'sunsetEpoch': 1726882021.0,
  'moonphase': 0.59,
  'conditions': 'Overcast',
  'description': 'Cloudy skies throughout the day.',
  'icon': 'cloudy',
  'stations': nan,
  'source': 'fcst',
  'City': 'Phoenix',
  'Temp_Range': 12.099999999999994,
  'Heat_Index': 84.20944151646408,
  'Severity_Score': 2.7404,
  'Condition_Code': nan,
  'Month': 9.0,
  'Season': 'Fall',
  'Day_of_Week': 'Friday',
  'Is_Weekend': False,
  'Health_Risk_Score': 8.853927351646409},
 {'datetime': '2024-09-21',
  'datetimeEpoch': 1726902000.0,
  'tempmax': 93.6,
  'tempmin': 77.4,
  'temp': 85.8,
  'feelslikemax': 89.0,
  'feelslikemin': 77.4,
  'feelslike': 83.1,
  'dew': 28.7,
  'humidity': 13.7,
  'precip': 0.0,
  'precipprob': 3.2,
  'precipcover': 0.0,
  'preciptype': nan,
  'snow': 0.0,
  'snowdepth': 0.0,
  'windgust': 14.1,
  'windspeed': 9.2,
  'winddir': 271.6,
  'pressure': 1009.3,
  'cloudcover': 1.8,
  'visibility': 15.0,
  'solarradiation': 268.6,
  'solarenergy': 23.3,
  'uvindex': 9.0,
  'severerisk': 10.0,
  'sunrise': '06:16:10',
  'sunriseEpoch': 1726924570.0,
  'sunset': '18:25:39',
  'sunsetEpoch': 1726968339.0,
  'moonphase': 0.63,
  'conditions': 'Clear',
  'description': 'Clear conditions throughout the day.',
  'icon': 'clear-day',
  'stations': nan,
  'source': 'fcst',
  'City': 'Phoenix',
  'Temp_Range': 16.19999999999999,
  'Heat_Index': 82.48084148677607,
  'Severity_Score': 3.21,
  'Condition_Code': 0.0,
  'Month': 9.0,
  'Season': 'Fall',
  'Day_of_Week': 'Saturday',
  'Is_Weekend': True,
  'Health_Risk_Score': 8.687854148677607},
 {'datetime': '2024-09-07',
  'datetimeEpoch': 1725692400.0,
  'tempmax': 89.0,
  'tempmin': 62.1,
  'temp': 73.3,
  'feelslikemax': 88.6,
  'feelslikemin': 62.1,
  'feelslike': 73.3,
  'dew': 59.8,
  'humidity': 66.3,
  'precip': 0.0,
  'precipprob': 0.0,
  'precipcover': 0.0,
  'preciptype': nan,
  'snow': 0.0,
  'snowdepth': 0.0,
  'windgust': 16.1,
  'windspeed': 9.2,
  'winddir': 311.1,
  'pressure': 1012.2,
  'cloudcover': 12.0,
  'visibility': 10.0,
  'solarradiation': 267.7,
  'solarenergy': 23.4,
  'uvindex': 9.0,
  'severerisk': 10.0,
  'sunrise': '06:43:31',
  'sunriseEpoch': 1725716611.0,
  'sunset': '19:26:34',
  'sunsetEpoch': 1725762394.0,
  'moonphase': 0.16,
  'conditions': 'Clear',
  'description': 'Clear conditions throughout the day.',
  'icon': 'clear-day',
  'stations': "['KSJC', 'KLVK', 'E6873', 'KHWD', 'KWVI', 'KOAK']",
  'source': 'comb',
  'City': 'San Jose',
  'Temp_Range': 26.9,
  'Heat_Index': 75.84249614266135,
  'Severity_Score': 3.41,
  'Condition_Code': 0.0,
  'Month': 9.0,
  'Season': 'Fall',
  'Day_of_Week': 'Saturday',
  'Is_Weekend': True,
  'Health_Risk_Score': 9.845079614266137},
 {'datetime': '2024-09-08',
  'datetimeEpoch': 1725778800.0,
  'tempmax': 89.0,
  'tempmin': 60.0,
  'temp': 72.4,
  'feelslikemax': 87.9,
  'feelslikemin': 60.0,
  'feelslike': 72.3,
  'dew': 57.6,
  'humidity': 62.5,
  'precip': 0.0,
  'precipprob': 0.0,
  'precipcover': 0.0,
  'preciptype': nan,
  'snow': 0.0,
  'snowdepth': 0.0,
  'windgust': 13.9,
  'windspeed': 8.1,
  'winddir': 310.2,
  'pressure': 1012.1,
  'cloudcover': 15.6,
  'visibility': 9.8,
  'solarradiation': 279.0,
  'solarenergy': 24.1,
  'uvindex': 9.0,
  'severerisk': 10.0,
  'sunrise': '06:44:20',
  'sunriseEpoch': 1725803060.0,
  'sunset': '19:25:03',
  'sunsetEpoch': 1725848703.0,
  'moonphase': 0.19,
  'conditions': 'Clear',
  'description': 'Clear conditions throughout the day.',
  'icon': 'clear-day',
  'stations': nan,
  'source': 'fcst',
  'City': 'San Jose',
  'Temp_Range': 29.0,
  'Heat_Index': 75.92701658370012,
  'Severity_Score': 3.1900000000000004,
  'Condition_Code': 0.0,
  'Month': 9.0,
  'Season': 'Fall',
  'Day_of_Week': 'Sunday',
  'Is_Weekend': True,
  'Health_Risk_Score': 9.586451658370011},
 {'datetime': '2024-09-09',
  'datetimeEpoch': 1725865200.0,
  'tempmax': 88.1,
  'tempmin': 63.1,
  'temp': 73.1,
  'feelslikemax': 87.4,
  'feelslikemin': 63.1,
  'feelslike': 73.0,
  'dew': 57.4,
  'humidity': 59.9,
  'precip': 0.0,
  'precipprob': 0.0,
  'precipcover': 0.0,
  'preciptype': nan,
  'snow': 0.0,
  'snowdepth': 0.0,
  'windgust': 16.1,
  'windspeed': 9.2,
  'winddir': 296.7,
  'pressure': 1013.0,
  'cloudcover': 11.0,
  'visibility': 10.1,
  'solarradiation': 311.5,
  'solarenergy': 27.0,
  'uvindex': 9.0,
  'severerisk': 10.0,
  'sunrise': '06:45:10',
  'sunriseEpoch': 1725889510.0,
  'sunset': '19:23:32',
  'sunsetEpoch': 1725935012.0,
  'moonphase': 0.22,
  'conditions': 'Clear',
  'description': 'Clear conditions throughout the day.',
  'icon': 'clear-day',
  'stations': nan,
  'source': 'fcst',
  'City': 'San Jose',
  'Temp_Range': 25.0,
  'Heat_Index': 76.45640756034118,
  'Severity_Score': 3.41,
  'Condition_Code': 0.0,
  'Month': 9.0,
  'Season': 'Fall',
  'Day_of_Week': 'Monday',
  'Is_Weekend': False,
  'Health_Risk_Score': 9.688230756034118},
 {'datetime': '2024-09-10',
  'datetimeEpoch': 1725951600.0,

In [7]:
len(data)

1000

In [8]:
DB_NAME = "UAHI"
COLLECTION_NAME = "urban_air_impact"
CONNECTION_URL = "mongodb+srv://srsingh2678:srsingh2678@cluster0.eaaga.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"

In [9]:
import pymongo

In [10]:
client = pymongo.MongoClient(CONNECTION_URL)
data_base = client[DB_NAME]
collection = data_base[COLLECTION_NAME]

rec = collection.insert_many(data)

In [11]:
records = collection.find()
records

In [12]:
for i, j in enumerate(records):
    print(f"{i}: {j}")

0: {'_id': ObjectId('67082952b0379fdf34f00c37'), 'datetime': '2024-09-07', 'datetimeEpoch': 1725692400.0, 'tempmax': 106.1, 'tempmin': 91.0, 'temp': 98.5, 'feelslikemax': 104.0, 'feelslikemin': 88.1, 'feelslike': 95.9, 'dew': 51.5, 'humidity': 21.0, 'precip': 0.0, 'precipprob': 5.0, 'precipcover': 0.0, 'preciptype': nan, 'snow': 0.0, 'snowdepth': 0.0, 'windgust': 26.3, 'windspeed': 13.7, 'winddir': 107.3, 'pressure': 1009.2, 'cloudcover': 25.0, 'visibility': 10.0, 'solarradiation': 261.4, 'solarenergy': 22.5, 'uvindex': 9.0, 'severerisk': 10.0, 'sunrise': '06:06:50', 'sunriseEpoch': 1725714410.0, 'sunset': '18:44:53', 'sunsetEpoch': 1725759893.0, 'moonphase': 0.16, 'conditions': 'Partially cloudy', 'description': 'Partly cloudy throughout the day.', 'icon': 'partly-cloudy-day', 'stations': "['KSDL', 'KDVT', 'AZM15', 'KPHX']", 'source': 'comb', 'City': 'Phoenix', 'Temp_Range': 15.099999999999994, 'Heat_Index': 95.91870310999995, 'Severity_Score': 4.43, 'Condition_Code': nan, 'Month': 9.0, 'Season': 'Fall', 'Day_of_Week': 'Saturday', 'Is_Weekend': True, 'Health_Risk_Score': 10.522170310999996}
1: {'_id': ObjectId('67082952b0379fdf34f00c38'), 'datetime': '2024-09-08', 'datetimeEpoch': 1725778800.0, 'tempmax': 103.9, 'tempmin': 87.0, 'temp': 95.4, 'feelslikemax': 100.5, 'feelslikemin': 84.7, 'feelslike': 92.3, 'dew': 48.7, 'humidity': 21.5, 'precip': 0.0, 'precipprob': 3.0, 'precipcover': 0.0, 'preciptype': nan, 'snow': 0.0, 'snowdepth': 0.0, 'windgust': 20.8, 'windspeed': 12.8, 'winddir': 101.5, 'pressure': 1008.8, 'cloudcover': 13.5, 'visibility': 10.1, 'solarradiation': 293.3, 'solarenergy': 25.2, 'uvindex': 9.0, 'severerisk': 10.0, 'sunrise': '06:07:30', 'sunriseEpoch': 1725800850.0, 'sunset': '18:43:32', 'sunsetEpoch': 1725846212.0, 'moonphase': 0.19, 'conditions': 'Clear', 'description': 'Clear conditions throughout the day.', 'icon': 'clear-day', 'stations': nan, 'source': 'fcst', 'City': 'Phoenix', 'Temp_Range': 16.900000000000006, 'Heat_Index': 92.28131624140006, 'Severity_Score': 3.88, 'Condition_Code': 0.0, 'Month': 9.0, 'Season': 'Fall', 'Day_of_Week': 'Sunday', 'Is_Weekend': True, 'Health_Risk_Score': 10.062331624140006}
2: {'_id': ObjectId('67082952b0379fdf34f00c39'), 'datetime': '2024-09-09', 'datetimeEpoch': 1725865200.0, 'tempmax': 105.0, 'tempmin': 83.9, 'temp': 94.7, 'feelslikemax': 99.9, 'feelslikemin': 81.6, 'feelslike': 90.6, 'dew': 41.7, 'humidity': 16.9, 'precip': 0.0, 'precipprob': 0.0, 'precipcover': 0.0, 'preciptype': nan, 'snow': 0.0, 'snowdepth': 0.0, 'windgust': 18.3, 'windspeed': 10.3, 'winddir': 90.8, 'pressure': 1009.4, 'cloudcover': 6.2, 'visibility': 10.1, 'solarradiation': 327.0, 'solarenergy': 28.2, 'uvindex': 9.0, 'severerisk': 10.0, 'sunrise': '06:08:10', 'sunriseEpoch': 1725887290.0, 'sunset': '18:42:10', 'sunsetEpoch': 1725932530.0, 'moonphase': 0.22, 'conditions': 'Clear', 'description': 'Clear conditions throughout the day.', 'icon': 'clear-day', 'stations': nan, 'source': 'fcst', 'City': 'Phoenix', 'Temp_Range': 21.099999999999994, 'Heat_Index': 90.5991651058291, 'Severity_Score': 3.63, 'Condition_Code': 0.0, 'Month': 9.0, 'Season': 'Fall', 'Day_of_Week': 'Monday', 'Is_Weekend': False, 'Health_Risk_Score': 9.67338651058291}
3: {'_id': ObjectId('67082952b0379fdf34f00c3a'), 'datetime': '2024-09-10', 'datetimeEpoch': 1725951600.0, 'tempmax': 106.1, 'tempmin': 81.2, 'temp': 93.9, 'feelslikemax': 100.6, 'feelslikemin': 79.5, 'feelslike': 89.8, 'dew': 39.1, 'humidity': 15.7, 'precip': 0.012, 'precipprob': 0.0, 'precipcover': 4.17, 'preciptype': "['rain']", 'snow': 0.0, 'snowdepth': 0.0, 'windgust': 10.5, 'windspeed': 5.4, 'winddir': 130.1, 'pressure': 1006.8, 'cloudcover': 4.9, 'visibility': 12.5, 'solarradiation': 276.8, 'solarenergy': 24.0, 'uvindex': 9.0, 'severerisk': 10.0, 'sunrise': '06:08:49', 'sunriseEpoch': 1725973729.0, 'sunset': '18:40:48', 'sunsetEpoch': 1726018848.0, 'moonphase': 0.25, 'conditions': 'Clear', 'description': 'Clear conditions throughout the day.', 'icon': 'clear-day', 'stations': nan, 'source': 'fcst', 'City': 'Phoenix', 'Temp_Range': 24.89999999999999, 'Heat_Index': 89.6388106900291, 'Severity_Score': 2.8512000000000004, 'Condition_Code': 0.0, 'Month': 9.0, 'Season': 'Fall', 'Day_of_Week': 'Tuesday', 'Is_Weekend': False, 'Health_Risk_Score': 9.411519469002911}
4: {'_id': ObjectId('67082952b0379fdf34f00c3b'), 'datetime': '2024-09-11', 'datetimeEpoch': 1726038000.0, 'tempmax': 106.1, 'tempmin': 82.1, 'temp': 94.0, 'feelslikemax': 101.0, 'feelslikemin': 80.0, 'feelslike': 90.0, 'dew': 40.1, 'humidity': 15.9, 'precip': 0.008, 'precipprob': 0.0, 'precipcover': 4.17, 'preciptype': "['rain']", 'snow': 0.0, 'snowdepth': 0.0, 'windgust': 15.9, 'windspeed': 8.1, 'winddir': 201.6, 'pressure': 1001.8, 'cloudcover': 5.7, 'visibility': 15.0, 'solarradiation': 274.9, 'solarenergy': 23.7, 'uvindex': 9.0, 'severerisk': 10.0, 'sunrise': '06:09:29', 'sunriseEpoch': 1726060169.0, 'sunset': '18:39:26', 'sunsetEpoch': 1726105166.0, 'moonphase': 0.29, 'conditions': 'Clear', 'description': 'Clear conditions throughout the day.', 'icon': 'clear-day', 'stations': nan, 'source': 'fcst', 'City': 'Phoenix', 'Temp_Range': 24.0, 'Heat_Index': 89.76041382170003, 'Severity_Score': 3.3908, 'Condition_Code': 0.0, 'Month': 9.0, 'Season': 'Fall', 'Day_of_Week': 'Wednesday', 'Is_Weekend': False, 'Health_Risk_Score': 9.515178582170003}
5: {'_id': ObjectId('67082952b0379fdf34f00c3c'), 'datetime': '2024-09-12', 'datetimeEpoch': 1726124400.0, 'tempmax': 103.0, 'tempmin': 81.6, 'temp': 91.5, 'feelslikemax': 98.1, 'feelslikemin': 79.9, 'feelslike': 87.9, 'dew': 41.6, 'humidity': 18.4, 'precip': 0.0, 'precipprob': 0.0, 'precipcover': 0.0, 'preciptype': nan, 'snow': 0.0, 'snowdepth': 0.0, 'windgust': 21.5, 'windspeed': 10.7, 'winddir': 201.9, 'pressure': 1000.8, 'cloudcover': 4.0, 'visibility': 15.0, 'solarradiation': 272.7, 'solarenergy': 23.6, 'uvindex': 9.0, 'severerisk': 10.0, 'sunrise': '06:10:09', 'sunriseEpoch': 1726146609.0, 'sunset': '18:38:04', 'sunsetEpoch': 1726191484.0, 'moonphase': 0.32, 'conditions': 'Clear', 'description': 'Clear conditions throughout the day.', 'icon': 'clear-day', 'stations': nan, 'source': 'fcst', 'City': 'Phoenix', 'Temp_Range': 21.40000000000001, 'Heat_Index': 87.60290690670004, 'Severity_Score': 3.95, 'Condition_Code': 0.0, 'Month': 9.0, 'Season': 'Fall', 'Day_of_Week': 'Thursday', 'Is_Weekend': False, 'Health_Risk_Score': 9.487090690670003}
6: {'_id': ObjectId('67082952b0379fdf34f00c3d'), 'datetime': '2024-09-13', 'datetimeEpoch': 1726210800.0, 'tempmax': 101.2, 'tempmin': 77.6, 'temp': 89.3, 'feelslikemax': 96.9, 'feelslikemin': 77.6, 'feelslike': 86.4, 'dew': 42.6, 'humidity': 20.4, 'precip': 0.0, 'precipprob': 0.0, 'precipcover': 0.0, 'preciptype': nan, 'snow': 0.0, 'snowdepth': 0.0, 'windgust': 14.3, 'windspeed': 7.2, 'winddir': 192.9, 'pressure': 1006.3, 'cloudcover': 7.2, 'visibility': 15.0, 'solarradiation': 269.5, 'solarenergy': 23.1, 'uvindex': 9.0, 'severerisk': 10.0, 'sunrise': '06:10:49', 'sunriseEpoch': 1726233049.0, 'sunset': '18:36:41', 'sunsetEpoch': 1726277801.0, 'moonphase': 0.36, 'conditions': 'Clear', 'description': 'Clear conditions throughout the day.', 'icon': 'clear-day', 'stations': nan, 'source': 'fcst', 'City': 'Phoenix', 'Temp_Range': 23.60000000000001, 'Heat_Index': 85.71988263588409, 'Severity_Score': 3.2300000000000004, 'Condition_Code': 0.0, 'Month': 9.0, 'Season': 'Fall', 'Day_of_Week': 'Friday', 'Is_Weekend': False, 'Health_Risk_Score': 9.23090826358841}
7: {'_id': ObjectId('67082952b0379fdf34f00c3e'), 'datetime': '2024-09-14', 'datetimeEpoch': 1726297200.0, 'tempmax': 99.4, 'tempmin': 78.2, 'temp': 89.1, 'feelslikemax': 96.1, 'feelslikemin': 78.2, 'feelslike': 86.8, 'dew': 48.4, 'humidity': 25.3, 'precip': 0.004, 'precipprob': 6.0, 'precipcover': 4.17, 'preciptype': "['rain']", 'snow': 0.0, 'snowdepth': 0.0, 'windgust': 12.1, 'windspeed': 5.4, 'winddir': 224.8, 'pressure': 1008.7, 'cloudcover': 9.6, 'visibility': 15.0, 'solarradiation': 262.5, 'solarenergy': 22.6, 'uvindex': 9.0, 'severerisk': 10.0, 'sunrise': '06:11:29', 'sunriseEpoch': 1726319489.0, 'sunset': '18:35:19', 'sunsetEpoch': 1726364119.0, 'moonphase': 0.39, 'conditions': 'Clear', 'description': 'Clear conditions throughout the day.', 'icon': 'clear-day', 'stations': nan, 'source': 'fcst', 'City': 'Phoenix', 'Temp_Range': 21.200000000000003, 'Heat_Index': 86.11250590362911, 'Severity_Score': 3.0104, 'Condition_Code': 0.0, 'Month': 9.0, 'Season': 'Fall', 'Day_of_Week': 'Saturday', 'Is_Weekend': True, 'Health_Risk_Score': 9.37288179036291}
8: {'_id': ObjectId('67082952b0379fdf34f00c3f'), 'datetime': '2024-09-15', 'datetimeEpoch': 1726383600.0, 'tempmax': 100.1, 'tempmin': 82.1, 'temp': 92.0, 'feelslikemax': 100.6, 'feelslikemin': 81.5, 'feelslike': 92.3, 'dew': 60.3, 'humidity': 35.8, 'precip': 0.012, 'precipprob': 12.9, 'precipcover': 4.17, 'preciptype': "['rain']", 'snow': 0.0, 'snowdepth': 0.0, 'windgust': 19.0, 'windspeed': 11.6, 'winddir': 254.3, 'pressure': 1007.3, 'cloudcover': 1.8, 'visibility': 14.0, 'solarradiation': 259.9, 'solarenergy': 22.3, 'uvindex': 8.0, 'severerisk': 30.0, 'sunrise': '06:12:09', 'sunriseEpoch': 1726405929.0, 'sunset': '18:33:56', 'sunsetEpoch': 1726450436.0, 'moonphase': 0.42, 'conditions': 'Clear', 'description': 'Clear conditions throughout the day.', 'icon': 'clear-day', 'stations': nan, 'source': 'fcst', 'City': 'Phoenix', 'Temp_Range': 18.0, 'Heat_Index': 92.16758603040012, 'Severity_Score': 3.5012, 'Condition_Code': 0.0, 'Month': 9.0, 'Season': 'Fall', 'Day_of_Week': 'Sunday', 'Is_Weekend': True, 'Health_Risk_Score': 10.470188203040012}
9: {'_id': ObjectId('67082952b0379fdf34f00c40'), 'datetime': '2024-09-16', 'datetimeEpoch': 1726470000.0, 'tempmax': 99.6, 'tempmin': 86.1, 'temp': 92.2, 'feelslikemax': 99.7, 'feelslikemin': 87.4, 'feelslike': 93.0, 'dew': 62.2, 'humidity': 37.8, 'precip': 0.0, 'precipprob': 12.9, 'precipcover': 0.0, 'preciptype': nan, 'snow': 0.0, 'snowdepth': 0.0, 'windgust': 17.7, 'windspeed': 12.1, 'winddir': 222.5, 'pressure': 1006.8, 'cloudcover': 12.2, 'visibility': 15.0, 'solarradiation': 245.3, 'solarenergy': 21.3, 'uvindex': 8.0, 'severerisk': 30.0, 'sunrise': '06:12:49', 'sunriseEpoch': 1726492369.0, 'sunset': '18:32:33', 'sunsetEpoch': 1726536753.0, 'moonphase': 0.46, 'conditions': 'Clear', 'description': 'Clear conditions throughout the day.', 'icon': 'clear-day', 'stations': nan, 'source': 'fcst', 'City': 'Phoenix', 'Temp_Range': 13.5, 'Heat_Index': 93.20895235529596, 'Severity_Score': 3.37, 'Condition_Code': 0.0, 'Month': 9.0, 'Season': 'Fall', 'Day_of_Week': 'Monday', 'Is_Weekend': False, 'Health_Risk_Score': 10.594755235529597}
10: {'_id': ObjectId('67082952b0379fdf34f00c41'), 'datetime': '2024-09-17', 'datetimeEpoch': 1726556400.0, 'tempmax': 100.7, 'tempmin': 85.7, 'temp': 92.2, 'feelslikemax': 98.5, 'feelslikemin': 85.2, 'feelslike': 91.2, 'dew': 57.3, 'humidity': 31.8, 'precip': 0.0, 'precipprob': 19.4, 'precipcover': 0.0, 'preciptype': nan, 'snow': 0.0, 'snowdepth': 0.0, 'windgust': 21.5, 'windspeed': 18.3, 'winddir': 234.6, 'pressure': 1005.6, 'cloudcover': 34.7, 'visibility': 15.0, 'solarradiation': 246.5, 'solarenergy': 21.2, 'uvindex': 8.0, 'severerisk': 10.0, 'sunrise': '06:13:29', 'sunriseEpoch': 1726578809.0, 'sunset': '18:31:10', 'sunsetEpoch': 1726623070.0, 'moonphase': 0.5, 'conditions': 'Partially cloudy', 'description': 'Partly cloudy throughout the day.', 'icon': 'partly-cloudy-day', 'stations': nan, 'source': 'fcst', 'City': 'Phoenix', 'Temp_Range': 15.0, 'Heat_Index': 91.13188727945612, 'Severity_Score': 3.75, 'Condition_Code': nan, 'Month': 9.0, 'Season': 'Fall', 'Day_of_Week': 'Tuesday', 'Is_Weekend': False, 'Health_Risk_Score': 10.305688727945611}
11: {'_id': ObjectId('67082952b0379fdf34f00c42'), 'datetime': '2024-09-18', 'datetimeEpoch': 1726642800.0, 'tempmax': 98.3, 'tempmin': 83.2, 'temp': 90.1, 'feelslikemax': 93.5, 'feelslikemin': 80.7, 'feelslike': 86.4, 'dew': 39.2, 'humidity': 17.4, 'precip': 0.0, 'precipprob': 6.5, 'precipcover': 0.0, 'preciptype': nan, 'snow': 0.0, 'snowdepth': 0.0, 'windgust': 15.7, 'windspeed': 10.1, 'winddir': 247.2, 'pressure': 1007.1, 'cloudcover': 0.0, 'visibility': 15.0, 'solarradiation': 267.3, 'solarenergy': 23.1, 'uvindex': 9.0, 'severerisk': 10.0, 'sunrise': '06:14:09', 'sunriseEpoch': 1726665249.0, 'sunset': '18:29:47', 'sunsetEpoch': 1726709387.0, 'moonphase': 0.52, 'conditions': 'Clear', 'description': 'Clear conditions throughout the day.', 'icon': 'clear-day', 'stations': nan, 'source': 'fcst', 'City': 'Phoenix', 'Temp_Range': 15.099999999999994, 'Heat_Index': 86.20360304705606, 'Severity_Score': 3.37, 'Condition_Code': 0.0, 'Month': 9.0, 'Season': 'Fall', 'Day_of_Week': 'Wednesday', 'Is_Weekend': False, 'Health_Risk_Score': 9.206740304705606}
12: {'_id': ObjectId('67082952b0379fdf34f00c43'), 'datetime': '2024-09-19', 'datetimeEpoch': 1726729200.0, 'tempmax': 97.4, 'tempmin': 81.8, 'temp': 89.1, 'feelslikemax': 92.2, 'feelslikemin': 79.6, 'feelslike': 85.3, 'dew': 29.0, 'humidity': 12.4, 'precip': 0.0, 'precipprob': 6.5, 'precipcover': 0.0, 'preciptype': nan, 'snow': 0.0, 'snowdepth': 0.0, 'windgust': 12.5, 'windspeed': 8.7, 'winddir': 258.9, 'pressure': 1007.8, 'cloudcover': 9.6, 'visibility': 15.0, 'solarradiation': 271.1, 'solarenergy': 23.4, 'uvindex': 9.0, 'severerisk': 10.0, 'sunrise': '06:14:50', 'sunriseEpoch': 1726751690.0, 'sunset': '18:28:24', 'sunsetEpoch': 1726795704.0, 'moonphase': 0.56, 'conditions': 'Clear', 'description': 'Clear conditions throughout the day.', 'icon': 'clear-day', 'stations': nan, 'source': 'fcst', 'City': 'Phoenix', 'Temp_Range': 15.600000000000009, 'Heat_Index': 85.14708197583606, 'Severity_Score': 3.05, 'Condition_Code': 0.0, 'Month': 9.0, 'Season': 'Fall', 'Day_of_Week': 'Thursday', 'Is_Weekend': False, 'Health_Risk_Score': 8.892908197583605}
13: {'_id': ObjectId('67082952b0379fdf34f00c44'), 'datetime': '2024-09-20', 'datetimeEpoch': 1726815600.0, 'tempmax': 94.6, 'tempmin': 82.5, 'temp': 87.9, 'feelslikemax': 89.9, 'feelslikemin': 80.1, 'feelslike': 84.4, 'dew': 35.5, 'humidity': 15.8, 'precip': 0.004, 'precipprob': 6.5, 'precipcover': 4.17, 'preciptype': "['rain']", 'snow': 0.0, 'snowdepth': 0.0, 'windgust': 15.4, 'windspeed': 9.8, 'winddir': 238.1, 'pressure': 1007.4, 'cloudcover': 92.0, 'visibility': 15.0, 'solarradiation': 175.8, 'solarenergy': 15.3, 'uvindex': 6.0, 'severerisk': 10.0, 'sunrise': '06:15:30', 'sunriseEpoch': 1726838130.0, 'sunset': '18:27:01', 'sunsetEpoch': 1726882021.0, 'moonphase': 0.59, 'conditions': 'Overcast', 'description': 'Cloudy skies throughout the day.', 'icon': 'cloudy', 'stations': nan, 'source': 'fcst', 'City': 'Phoenix', 'Temp_Range': 12.099999999999994, 'Heat_Index': 84.20944151646408, 'Severity_Score': 2.7404, 'Condition_Code': nan, 'Month': 9.0, 'Season': 'Fall', 'Day_of_Week': 'Friday', 'Is_Weekend': False, 'Health_Risk_Score': 8.853927351646409}
14: {'_id': ObjectId('67082952b0379fdf34f00c45'), 'datetime': '2024-09-21', 'datetimeEpoch': 1726902000.0, 'tempmax': 93.6, 'tempmin': 77.4, 'temp': 85.8, 'feelslikemax': 89.0, 'feelslikemin': 77.4, 'feelslike': 83.1, 'dew': 28.7, 'humidity': 13.7, 'precip': 0.0, 'precipprob': 3.2, 'precipcover': 0.0, 'preciptype': nan, 'snow': 0.0, 'snowdepth': 0.0, 'windgust': 14.1, 'windspeed': 9.2, 'winddir': 271.6, 'pressure': 1009.3, 'cloudcover': 1.8, 'visibility': 15.0, 'solarradiation': 268.6, 'solarenergy': 23.3, 'uvindex': 9.0, 'severerisk': 10.0, 'sunrise': '06:16:10', 'sunriseEpoch': 1726924570.0, 'sunset': '18:25:39', 'sunsetEpoch': 1726968339.0, 'moonphase': 0.63, 'conditions': 'Clear', 'description': 'Clear conditions throughout the day.', 'icon': 'clear-day', 'stations': nan, 'source': 'fcst', 'City': 'Phoenix', 'Temp_Range': 16.19999999999999, 'Heat_Index': 82.48084148677607, 'Severity_Score': 3.21, 'Condition_Code': 0.0, 'Month': 9.0, 'Season': 'Fall', 'Day_of_Week': 'Saturday', 'Is_Weekend': True, 'Health_Risk_Score': 8.687854148677607}
15: {'_id': ObjectId('67082952b0379fdf34f00c46'), 'datetime': '2024-09-07', 'datetimeEpoch': 1725692400.0, 'tempmax': 89.0, 'tempmin': 62.1, 'temp': 73.3, 'feelslikemax': 88.6, 'feelslikemin': 62.1, 'feelslike': 73.3, 'dew': 59.8, 'humidity': 66.3, 'precip': 0.0, 'precipprob': 0.0, 'precipcover': 0.0, 'preciptype': nan, 'snow': 0.0, 'snowdepth': 0.0, 'windgust': 16.1, 'windspeed': 9.2, 'winddir': 311.1, 'pressure': 1012.2, 'cloudcover': 12.0, 'visibility': 10.0, 'solarradiation': 267.7, 'solarenergy': 23.4, 'uvindex': 9.0, 'severerisk': 10.0, 'sunrise': '06:43:31', 'sunriseEpoch': 1725716611.0, 'sunset': '19:26:34', 'sunsetEpoch': 1725762394.0, 'moonphase': 0.16, 'conditions': 'Clear', 'description': 'Clear conditions throughout the day.', 'icon': 'clear-day', 'stations': "['KSJC', 'KLVK', 'E6873', 'KHWD', 'KWVI', 'KOAK']", 'source': 'comb', 'City': 'San Jose', 'Temp_Range': 26.9, 'Heat_Index': 75.84249614266135, 'Severity_Score': 3.41, 'Condition_Code': 0.0, 'Month': 9.0, 'Season': 'Fall', 'Day_of_Week': 'Saturday', 'Is_Weekend': True, 'Health_Risk_Score': 9.845079614266137}
16: {'_id': ObjectId('67082952b0379fdf34f00c47'), 'datetime': '2024-09-08', 'datetimeEpoch': 1725778800.0, 'tempmax': 89.0, 'tempmin': 60.0, 'temp': 72.4, 'feelslikemax': 87.9, 'feelslikemin': 60.0, 'feelslike': 72.3, 'dew': 57.6, 'humidity': 62.5, 'precip': 0.0, 'precipprob': 0.0, 'precipcover': 0.0, 'preciptype': nan, 'snow': 0.0, 'snowdepth': 0.0, 'windgust': 13.9, 'windspeed': 8.1, 'winddir': 310.2, 'pressure': 1012.1, 'cloudcover': 15.6, 'visibility': 9.8, 'solarradiation': 279.0, 'solarenergy': 24.1, 'uvindex': 9.0, 'severerisk': 10.0, 'sunrise': '06:44:20', 'sunriseEpoch': 1725803060.0, 'sunset': '19:25:03', 'sunsetEpoch': 1725848703.0, 'moonphase': 0.19, 'conditions': 'Clear', 'description': 'Clear conditions throughout the day.', 'icon': 'clear-day', 'stations': nan, 'source': 'fcst', 'City': 'San Jose', 'Temp_Range': 29.0, 'Heat_Index': 75.92701658370012, 'Severity_Score': 3.1900000000000004, 'Condition_Code': 0.0, 'Month': 9.0, 'Season': 'Fall', 'Day_of_Week': 'Sunday', 'Is_Weekend': True, 'Health_Risk_Score': 9.586451658370011}
17: {'_id': ObjectId('67082952b0379fdf34f00c48'), 'datetime': '2024-09-09', 'datetimeEpoch': 1725865200.0, 'tempmax': 88.1, 'tempmin': 63.1, 'temp': 73.1, 'feelslikemax': 87.4, 'feelslikemin': 63.1, 'feelslike': 73.0, 'dew': 57.4, 'humidity': 59.9, 'precip': 0.0, 'precipprob': 0.0, 'precipcover': 0.0, 'preciptype': nan, 'snow': 0.0, 'snowdepth': 0.0, 'windgust': 16.1, 'windspeed': 9.2, 'winddir': 296.7, 'pressure': 1013.0, 'cloudcover': 11.0, 'visibility': 10.1, 'solarradiation': 311.5, 'solarenergy': 27.0, 'uvindex': 9.0, 'severerisk': 10.0, 'sunrise': '06:45:10', 'sunriseEpoch': 1725889510.0, 'sunset': '19:23:32', 'sunsetEpoch': 1725935012.0, 'moonphase': 0.22, 'conditions': 'Clear', 'description': 'Clear conditions throughout the day.', 'icon': 'clear-day', 'stations': nan, 'source': 'fcst', 'City': 'San Jose', 'Temp_Range': 25.0, 'Heat_Index': 76.45640756034118, 'Severity_Score': 3.41, 'Condition_Code': 0.0, 'Month': 9.0, 'Season': 'Fall', 'Day_of_Week': 'Monday', 'Is_Weekend': False, 'Health_Risk_Score': 9.688230756034118}

In [13]:
df = pd.DataFrame(list(collection.find()))
df.head()

,_id,datetime,datetimeEpoch,tempmax,tempmin,temp,feelslikemax,feelslikemin,feelslike,dew,...,City,Temp_Range,Heat_Index,Severity_Score,Condition_Code,Month,Season,Day_of_Week,Is_Weekend,Health_Risk_Score
0,67082952b0379fdf34f00c37,2024-09-07,1.725692e+09,106.1,91.0,98.5,104.0,88.1,95.9,51.5,...,Phoenix,15.1,95.918703,4.4300,NaN,9.0,Fall,Saturday,True,10.522170
1,67082952b0379fdf34f00c38,2024-09-08,1.725779e+09,103.9,87.0,95.4,100.5,84.7,92.3,48.7,...,Phoenix,16.9,92.281316,3.8800,0.0,9.0,Fall,Sunday,True,10.062332
2,67082952b0379fdf34f00c39,2024-09-09,1.725865e+09,105.0,83.9,94.7,99.9,81.6,90.6,41.7,...,Phoenix,21.1,90.599165,3.6300,0.0,9.0,Fall,Monday,False,9.673387
3,67082952b0379fdf34f00c3a,2024-09-10,1.725952e+09,106.1,81.2,93.9,100.6,79.5,89.8,39.1,...,Phoenix,24.9,89.638811,2.8512,0.0,9.0,Fall,Tuesday,False,9.411519
4,67082952b0379fdf34f00c3b,2024-09-11,1.726038e+09,106.1,82.1,94.0,101.0,80.0,90.0,40.1,...,Phoenix,24.0,89.760414,3.3908,0.0,9.0,Fall,Wednesday,False,9.515179

In [14]:
if "_id" in df.columns.to_list():
    df = df.drop(columns=["_id"], axis=1)

In [15]:
df.head()

,datetime,datetimeEpoch,tempmax,tempmin,temp,feelslikemax,feelslikemin,feelslike,dew,humidity,...,City,Temp_Range,Heat_Index,Severity_Score,Condition_Code,Month,Season,Day_of_Week,Is_Weekend,Health_Risk_Score
0,2024-09-07,1.725692e+09,106.1,91.0,98.5,104.0,88.1,95.9,51.5,21.0,...,Phoenix,15.1,95.918703,4.4300,NaN,9.0,Fall,Saturday,True,10.522170
1,2024-09-08,1.725779e+09,103.9,87.0,95.4,100.5,84.7,92.3,48.7,21.5,...,Phoenix,16.9,92.281316,3.8800,0.0,9.0,Fall,Sunday,True,10.062332
2,2024-09-09,1.725865e+09,105.0,83.9,94.7,99.9,81.6,90.6,41.7,16.9,...,Phoenix,21.1,90.599165,3.6300,0.0,9.0,Fall,Monday,False,9.673387
3,2024-09-10,1.725952e+09,106.1,81.2,93.9,100.6,79.5,89.8,39.1,15.7,...,Phoenix,24.9,89.638811,2.8512,0.0,9.0,Fall,Tuesday,False,9.411519
4,2024-09-11,1.726038e+09,106.1,82.1,94.0,101.0,80.0,90.0,40.1,15.9,...,Phoenix,24.0,89.760414,3.3908,0.0,9.0,Fall,Wednesday,False,9.515179